package io.hoony.paymentconsumer;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import({PaymentEventHandler.class, PaymentEventHandlerTest.ClockConfiguration.class})
class PaymentEventHandlerTest {

    @org.springframework.beans.factory.annotation.Autowired
    private PaymentEventHandler handler;

    @org.springframework.beans.factory.annotation.Autowired
    private JdbcTemplate jdbc;

    @BeforeEach
    void createSchema() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS processed_events (
                    consumer_group VARCHAR(100) NOT NULL,
                    event_id CHAR(36) NOT NULL,
                    processed_at TIMESTAMP NOT NULL,
                    PRIMARY KEY (consumer_group, event_id)
                )
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS payment_event_effects (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    consumer_group VARCHAR(100) NOT NULL,
                    event_id CHAR(36) NOT NULL,
                    aggregate_id CHAR(36) NOT NULL,
                    event_type VARCHAR(64) NOT NULL,
                    schema_version INT NOT NULL,
                    occurred_at TIMESTAMP NOT NULL,
                    processed_at TIMESTAMP NOT NULL,
                    CONSTRAINT uk_payment_event_effect UNIQUE (consumer_group, event_id)
                )
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS consumer_aggregate_progress (
                    consumer_group VARCHAR(100) NOT NULL,
                    aggregate_id CHAR(36) NOT NULL,
                    last_occurred_at TIMESTAMP NOT NULL,
                    last_event_id CHAR(36) NOT NULL,
                    PRIMARY KEY (consumer_group, aggregate_id)
                )
                """);
        jdbc.update("DELETE FROM consumer_aggregate_progress");
        jdbc.update("DELETE FROM payment_event_effects");
        jdbc.update("DELETE FROM processed_events");
    }

    @Test
    void duplicateEventProducesOneSideEffect() {
        PaymentEventEnvelope event = event(UUID.randomUUID(), "2026-07-31T09:59:00Z");

        assertThat(handler.handle(event)).isEqualTo(PaymentEventHandler.Result.PROCESSED);
        assertThat(handler.handle(event)).isEqualTo(PaymentEventHandler.Result.DUPLICATE);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM processed_events", Long.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM payment_event_effects", Long.class)).isEqualTo(1);
    }

    @Test
    void olderEventDoesNotOverwriteAggregateProgress() {
        UUID aggregateId = UUID.randomUUID();
        PaymentEventEnvelope newer = event(aggregateId, "2026-07-31T09:59:00Z");
        PaymentEventEnvelope older = event(aggregateId, "2026-07-31T09:58:00Z");

        assertThat(handler.handle(newer)).isEqualTo(PaymentEventHandler.Result.PROCESSED);
        assertThat(handler.handle(older)).isEqualTo(PaymentEventHandler.Result.OUT_OF_ORDER);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM payment_event_effects", Long.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject(
                "SELECT last_event_id FROM consumer_aggregate_progress WHERE aggregate_id = ?",
                String.class,
                aggregateId.toString()
        )).isEqualTo(newer.eventId().toString());
    }

    private PaymentEventEnvelope event(UUID aggregateId, String occurredAt) {
        return new PaymentEventEnvelope(
                UUID.randomUUID(),
                aggregateId,
                "PAYMENT_APPROVED",
                1,
                Instant.parse(occurredAt),
                null
        );
    }

    @TestConfiguration
    static class ClockConfiguration {
        @Bean
        Clock clock() {
            return Clock.fixed(Instant.parse("2026-07-31T10:00:00Z"), ZoneOffset.UTC);
        }
    }
}